- name: install mysql_db packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - mysql-common
      - mysql-server
      - python-mysqldb
  become: yes

- name: copy db configuration
  command: cp /etc/mysql/my.cnf /root/.my.cnf
  become: yes

- name: add mysql user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: '*.*:ALL'
    state: present
  become: yes
  
- name: create WP mysql db
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: "{{ wp_db_user }}"
    login_password: "{{ wp_db_password }}"
  become: yes
